Repository accordproject/cicero-template-library, pull requests merged in 2019-10, with the labels that each got.

#262 docs(CONTRIBUTING): fix broken links in docs - I253
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#264 docs(README): centered logo, adds slack badge, adds license badge
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#266 fix(src): swap buyer and seller - I259
  src/minilatedeliveryandpenalty-capped/grammar/template.tem
  src/minilatedeliveryandpenalty-capped/package.json
  src/minilatedeliveryandpenalty-capped/test/logic.feature
  src/minilatedeliveryandpenalty-payment/grammar/template.tem
  src/minilatedeliveryandpenalty-payment/package.json
  src/minilatedeliveryandpenalty-payment/test/logic.feature
  src/minilatedeliveryandpenalty/grammar/template.tem
  src/minilatedeliveryandpenalty/package.json
  src/minilatedeliveryandpenalty/test/logic.feature
Labels: Difficulty: Starter, Hacktoberfest, Type: Breaking Change 💥, Type: Bug 🐛

#272 doc(README): Centering the Title and Badges
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#273 docs(README): fix typo
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#274 docs(CONTRIBUTING): fix grammar
  CONTRIBUTING.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#283 feat(docs): add ecosystem table
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#280 docs(*): update markdown files and fix typos - I257
  CONTRIBUTING.md
  DEVELOPERS.md
  README.md
Labels: Difficulty: Starter, Hacktoberfest, Type: Documentation 📝

#282 chore(gitignore): add thumbs.db
  .gitignore
Labels: Difficulty: Starter, Hacktoberfest

#286 fix(minilatedeliveryandpenalty): switch buyer and seller - I259
  src/minilatedeliveryandpenalty/sample.txt
Labels: Difficulty: Starter, Hacktoberfest
